p1 = input("Diz o nome do teu produto 1.")
qp1 = int(input("Diz a quantidade de produto 1 que tens em stock."))
pr1 = int(input("Diz o preço unitário do teu produto 1."))
vt1 =(qp1*pr1)
p2 = input("Diz o nome do teu produto 2.")
qp2 = int(input("Diz a quantidade de produto 2 que tens em stock."))
pr2 = int(input("Diz o preço unitário do teu produto 2."))
vt2 =(qp2*pr2)
p3 = input("Diz o nome do teu produto 3.")
qp3 = int(input("Diz a quantidade de produto 3 que tens em stock."))
pr3 = int(input("Diz o preço unitário do teu produto 3."))
vt3 =(qp3*pr3)
tt =(vt3+vt1+vt2)
print(f'"Tu tens em stock, {vt1}€ em {p1}, {vt2}€ em {p2} e {vt3}€ em {p3}."')
print(f'"O valor total de todos os teus produtos é de {tt}€."')
