m = int(input("Escolhe uma medida em metros."))
km =(m*0.001)
hm =(m*0.01)
dam =(m*0.1)
dm =(m*10)
cm =(m*100)
mm =(m*1000)
print(f'"A tua medida nas seguintes unidades é:"')
print(f'"{km} km"')
print(f'"{hm} hm"')
print(f'"{dam} dam"')
print(f'"{cm} cm"')
print(f'"{dm} dm"')
print(f'"{mm} mm"')
